CREATE VIEW GCG_4204_EXT_DESC AS SELECT IM.PART, IM.PRODUCT_LINE, IM.FLAG_INACTIVE, IM.OBSOLETE_FLAG, RTrim(IM.DESCRIPTION) AS DESCRIPTION, 
( RTrim(IM2.DESCRIPTION_2) +' ' + RTrim(IM2.DESCRIPTION_3) +' '+ 
EXT.TEXT) AS VIM_EXTEND_DESC, 
RTrim(IM.CODE_SORT) AS CODE_SORT , RTrim(IM2.NAME_VENDOR) AS NAME_VENDOR, RTrim(IM2.TEXT_INFO1) AS TEXT_INFO1, RTrim(IM2.TEXT_INFO2) AS TEXT_INFO2 
FROM INVENTORY_MSTR IM LEFT OUTER JOIN INVENTORY_MST2 IM2 ON IM2.PART=IM.PART AND IM2.LOCATION=IM.LOCATION 
LEFT OUTER JOIN INV_EXTRA_TEXT EXT ON EXT.PART=IM.PART