SELECT * FROM INV_EXTRA_TEXT
WHERE
 REPLACE(REPLACE(REPLACE(TEXT,CHAR(13),' '),CHAR(10),''),CHAR(9),'') != TEXT;

 
UPDATE INV_EXTRA_TEXT
SET TEXT =  REPLACE(REPLACE(REPLACE(TEXT,CHAR(13),' '),CHAR(10),''),CHAR(9),'') WHERE
REPLACE(REPLACE(REPLACE(TEXT,CHAR(13),' '),CHAR(10),''),CHAR(9),'') != TEXT;
 